version: "3"
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always     
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: my_cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: my_datacenter  
  cassandra-api:
    image: resulguldibi/cassandra-api
    container_name: cassandra-api
    restart: always
    depends_on:
      - cassandra
    links:
      - cassandra  
    ports:
      - 8080:8080
